version: '3.1'

services:

  wp:
    container_name: wp
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: S3cr3T!
    depends_on:
    - wp-db
    links:
    - wp-db:mysql

  wp-db:
    container_name: wp-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: S3cr3T!