version: '3.1'

services:

  wp:
    image: ozguramac/penr-oz-wp
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: S3cr3T!

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: S3cr3T!